detect/urls.py
from django.urls import path

from . import views

app_name = "detect"

urlpatterns = [
    path('', views.home_page, name="home"),
    path('student_login/', views.student_login, name="student_login"),
    path('student_logout/', views.student_logout, name="student_logout"),
    path('theory/', views.theory1, name="theory_list"),
    path('theory/1/', views.theory1, name="theory1"),
    path('theory/2/', views.theory2, name="theory2"),
    path('theory/3/', views.theory3, name="theory3"),
    path('laboratory/', views.lab1_example, name="lab1_example"),
    path('laboratory/1/', views.laboratory1, name="laboratory1"),
    path('laboratory/2/', views.laboratory2, name="laboratory2"),
    path('laboratory/3/', views.laboratory3, name="laboratory3"),
    path('laboratory/4/', views.laboratory4, name="laboratory4"),
    path('test/', views.final_test, name="final_test"),
    path('result_is_db/', views.result_is_db, name="result"),
]

diploma/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('', RedirectView.as_view(url='/detect/'), name="home"),
    path('admin/', admin.site.urls),
    path('detect/', include('detect.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = views.m500
handler410 = views.m410
handler405 = views.m405
handler404 = views.m404
handler403 = views.m403
handler400 = views.m400
handler304 = views.m304

detect/forms.py
from django import forms

from modulation_script import Modem
from .consts import modulation_choices
from .models import Student, Modulation, TemporaryImage
from .utils import get_signals, get_signal_image, get_signal_stars, get_modem_by_modulation


class DemodulateInfluenceSNRFrom(forms.Form):
    modulation = forms.ChoiceField(label='Тип манипуляции', choices=modulation_choices)
    snr = forms.DecimalField(label='SNR', initial=6, decimal_places=2, max_digits=4, min_value=1)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['snr'].widget.attrs['placeholder'] = '12.55'
        self.fields['snr'].widget.attrs['class'] = 'is-invalid'

    @staticmethod
    def get_modulation_img_path(modem: Modem, modulation_position: int, modulation: str) -> str:
        """Путь до изображения сигнального созвездия для выбранного типа модуляции"""
        modulation_bd, create = Modulation.objects.get_or_create(method=modulation)
        if not modulation_bd.stars_image:
            content = get_signal_stars(modem, modulation_position, modulation)
            modulation_bd.stars_image.save(f"{modulation}.png", content)
        return modulation_bd.stars_image.url

    @staticmethod
    def calculate_percent(modem: Modem, modulation_position: int, snr: float) -> float:
        """Расчёт процента ошибочно декодированных сообщений для данного типа модуляции и SNR"""
        success_demodulate = 0
        number_checks = 1000
        for i in range(number_checks):
            messages = get_signals(modem, modulation_position, snr)
            original_message, demodulated_message = messages[0], messages[1]
            if demodulated_message == original_message:
                success_demodulate += 1
        return round(100 - success_demodulate * 100 / number_checks, 3)

    def get_context_data(self):
        snr = float(self.cleaned_data['snr'])
        modulation = self.cleaned_data['modulation']
        modulation_position, modulation_type = modulation.split('-')
        modulation_position = int(modulation_position)
        modem = get_modem_by_modulation(modulation_type, modulation_position)
        # Создание сигналов и сохранение изображений
        original_msg, demodulated_msg, modulated_signal, gaussian_signal = get_signals(modem, modulation_position, snr)
        modulated_signal_image = TemporaryImage.objects.create()
        modulated_signal_image.image.save(f'modulated_{modulated_signal_image.id}.png',
                                          get_signal_image(modulated_signal))
        signal_with_gauss_image = TemporaryImage.objects.create()
        signal_with_gauss_image.image.save(f'gaussian_{signal_with_gauss_image.id}.png',
                                           get_signal_image(gaussian_signal))
        # Формирование вывода о влиянии SNR на выбранный тип модуляции
        percent_errors = self.calculate_percent(modem, modulation_position, snr)
        if 0 < percent_errors <= 1:
            is_complete = True
        else:
            is_complete = False
        return {'original_message': original_msg,
                'demodulated_message': demodulated_msg,
                'path_to_modulated_signal': modulated_signal_image.image.url,
                'path_to_signal_with_gauss': signal_with_gauss_image.image.url,
                'modulation_image_path': self.get_modulation_img_path(modem, modulation_position, modulation),
                'percent_errors': percent_errors,
                'is_complete': is_complete,
                'modulation': modulation,
                'snr': snr,
                }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'surname', 'group')

    def get_user(self):
        name = self.cleaned_data['name']
        surname = self.cleaned_data['surname']
        group = self.cleaned_data['group']
        student = Student.objects.filter(name__iexact=name, surname__iexact=surname, group__iexact=group).first()
        if student:
            return student
        return Student.objects.create(name=name.capitalize(), surname=surname.capitalize(), group=group.upper())

detect/views.py
import random
import warnings

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_GET, require_http_methods

from .forms import StudentForm, DemodulateInfluenceSNRFrom
from .models import Student, StudentLab1
from .utils import for_test, get_lab2_tasks_by_student, get_lab3_tasks_by_student, get_lab4_by_student

warnings.filterwarnings('ignore')


@require_http_methods(["GET", "POST"])
def student_login(request: WSGIRequest):
    next_page = request.GET.get('next')
    form = StudentForm
    if request.method == "POST":
        form = form(request.POST)
        if form.is_valid():
            student = form.get_user()
            login(request, student)
            return HttpResponseRedirect(next_page or reverse('detect:lab1_example'))
    return render(request, 'detect/login.html', {'form': form})


@require_http_methods(["GET", "POST"])
def student_logout(request: WSGIRequest):
    logout(request)
    return HttpResponseRedirect(reverse('detect:home'))


@require_GET
def home_page(request: WSGIRequest):
    """Главная страница"""
    with open('theory/glavn.txt', 'r', encoding='utf-8') as file:
        text = file.read()
    data = {"header": "Лабораторная работа на тему 'Детектирование сигналов в современных системах связи'",
            "text": text}
    return render(request, 'detect/home.html', context=data)


@require_GET
def theory1(request: WSGIRequest):
    with open('theory/theory1.txt', 'r', encoding='UTF-8') as f:
        text = f.readlines()
    data = {"header": "1. Общие сведения о задаче детектирования",
            "text": text}
    return render(request, 'detect/theory1.html', context=data)


@require_GET
def theory2(request: WSGIRequest):
    with open('theory/theory2.txt', 'r', encoding='UTF-8') as file:
        text = file.readlines()
    data = {"header": "2. Классификация методов детектирования",
            "text": text
            }
    return render(request, 'detect/theory2.html', context=data)


@require_GET
def theory3(request: WSGIRequest):
    with open('theory/theory3.txt', 'r', encoding='UTF-8') as file:
        text = file.readlines()
    data = {"header": "3. Перспективы развития методов детектирования",
            "text": text
            }
    return render(request, 'detect/theory3.html', context=data)


@login_required(login_url="/detect/student_login/")
@require_GET
def lab1_example(request: WSGIRequest):
    return render(request, 'detect/lab1_example.html', {'form': DemodulateInfluenceSNRFrom})


@login_required(login_url="/detect/student_login/")
@require_http_methods(["POST", "GET"])
@never_cache
def laboratory1(request: WSGIRequest):
    form = DemodulateInfluenceSNRFrom
    if request.method == "POST":
        form = form(request.POST)
        if form.is_valid():
            data = form.get_context_data()
            if data['is_complete']:
                StudentLab1.objects.get_or_create(student=request.user, modulation=data['modulation'], is_complete=True)
            data['form'] = form
            return render(request, 'detect/laboratory1.html', context=data)
    return render(request, 'detect/lab1_example.html', context={"form": form, 'hide_example': True})


@login_required(login_url="/detect/student_login/")
@require_http_methods(["POST", "GET"])
@never_cache
def laboratory2(request: WSGIRequest):
    lab2_tasks = get_lab2_tasks_by_student(request.user)
    if request.method == "POST":
        for lab2 in lab2_tasks:
            if not lab2.is_complete and request.POST.get(lab2.modulation) == lab2.signal:
                lab2.is_complete = True
                lab2.save()
    return render(request, 'detect/laboratory2.html', context={'lab2_tasks': lab2_tasks})


@login_required(login_url="/detect/student_login/")
@require_http_methods(["POST", "GET"])
@never_cache
def laboratory3(request: WSGIRequest):
    lab3_tasks = get_lab3_tasks_by_student(request.user)
    if request.method == "POST":
        for lab3 in lab3_tasks:
            if not lab3.is_complete and request.POST.get(f'signal-{lab3.multiplier}') == lab3.signal:
                lab3.is_complete = True
                lab3.save()
    return render(request, 'detect/laboratory3.html', context={"lab3_tasks": lab3_tasks})


@login_required(login_url="/detect/student_login/")
@require_http_methods(["POST", "GET"])
@never_cache
def laboratory4(request: WSGIRequest):
    lab4 = get_lab4_by_student(request.user)
    if request.method == "POST":
        if not lab4.is_complete and request.POST.get('signal') == lab4.signal:
            lab4.is_complete = True
            lab4.save()
    return render(request, 'detect/laboratory4.html', context={"lab4": lab4})


# Запоминает вопросы пользователя
otveti_for_users = []
otveti_slovar = {}


@require_GET
@never_cache
def result_is_db(request: WSGIRequest):
    """Возвращает информацию о статусе выполнения заданий студентами"""
    # todo отображать прогресс по лабам и тесту в виде таблицы.
    page_number = request.GET.get('page')
    students = Student.objects.all()
    paginator = Paginator(students, 50)
    students_results = []
    for index, student in enumerate(paginator.get_page(page_number), start=1):
        student: Student
        result = f"{index}) {student}"
        result += f" прошёл тест на {student.test_percent}% "
        result += f"(дата прохождения: {student.create_dt.strftime('%d.%m.%Y')})"
        students_results.append(result)
    return render(request, 'detect/result_is_db.html', context={"spisok": students_results})


@login_required(login_url="/detect/student_login/")
@require_http_methods(["GET", "POST"])
@never_cache
def final_test(request: WSGIRequest):
    # todo привязать набор вопросов к пользователю
    global otveti_for_users
    c = 0
    form = StudentForm()  # Создаются поля для ввода Имени, Фамилии и Группы
    if request.method == "POST":  # Проверяется, вводил ли пользователь свои данные и ответил ли на вопросы
        # Т.к. изначально при входе на страницу ничего не введено, то эта функция вызывается после else (поэтому сначала надо смотреть на работу этого пункта)
        name = request.POST.get("name")
        surname = request.POST.get("family")
        group = request.POST.get("group")
        pk = request.POST.get("id")
        voprosi, otveti = otveti_slovar.get(pk)[0], otveti_slovar.get(pk)[1]
        for i in range(len(voprosi)):  # Перебирает каждый ответ, выбранный пользователем
            a = request.POST.get(
                str(voprosi[i][5]))  # Извлекаю из каждого вопроса варианты ответов, выбранные пользователем
            if a == otveti[i]:  # Сверяю извлеченный ответ с правильным ответом
                c += 1
        test_percent = 100 * c // len(voprosi)  # Подсчёт процента правильных ответов пользователя

        if test_percent >= 80:  # Если процент больше 80, то создаю в БД строку, в которой записываются Данные пользователя и процент правильных ответов,
            # а также отправляет пользователя на страницу, где будет написан результат выполнения теста
            Student.objects.create(name=name, surname=surname, group=group, test_percent=test_percent)
            otveti_for_users.remove(pk)
            otveti_slovar.pop(pk)
            result = "{0} {1} из группы {2}. Вы прошли тест на: {3}%. Покажите результат преподавателю!".format(name,
                                                                                                                surname,
                                                                                                                group,
                                                                                                                test_percent)
            return render(request, 'detect/result.html', context={"result": result})
        else:  # Если процент выполнения меньше 80, то заново формируются блоки вопросов и ответов, пользователь отправляется заново проходить тест
            zagolovok, voprosi, otveti = for_test('tests/test1.txt', 15)
            otveti_for_users.remove(pk)
            otveti_slovar.pop(pk)
            pk = znach(voprosi, otveti)
            otveti_for_users.append(pk)
            result = "Вы прошли тест на: {}%. Попробуйте ещё раз!".format(test_percent)
            return render(request, 'detect/final_test.html',
                          context={"zagolovok": zagolovok, "voprosi": voprosi, "form": form, "result": result,
                                   "id": pk})
    else:  # Когда пользователь только заходит на страницу теста, то для него формируются вопросы и ответы, которые запоминаются в функции func5
        zagolovok, voprosi, otveti = for_test('tests/test1.txt',
                                              15)  # Получение из файла перемешанных вопросов и ответов к ним.
        pk = znach(voprosi, otveti)
        otveti_for_users.append(pk)
        result = "Введите свои данные и проходите тест:"
        return render(request, 'detect/final_test.html',
                      context={"zagolovok": zagolovok, "voprosi": voprosi, "form": form, "result": result,
                               "id": pk})


def znach(voprosi, otveti):
    # Функция принимает блок вопросов и ответов, сохраняет их под определённым id и отправляет этот id пользователю
    global otveti_slovar
    t = random.randint(-99999999, 99999999)
    while otveti_slovar.get(str(t)) != None:
        t = random.randint(-99999999, 99999999)
    otveti_slovar[str(t)] = [voprosi, otveti]
    return str(t)

detect/templates/detect/base_theory.html
{% extends "detect/base.html" %}
{% load static %}

{% block secondary-navbar %}
    <nav class="bot-menu">
        <ul class="menu-dop">
            <li><a href="{% url 'detect:theory1' %}">1. Общие сведения о задаче детектирования</a></li>
            <li><a href="{% url 'detect:theory2' %}">2. Классификация методов детектирования</a></li>
            <li><a href="{% url 'detect:theory3' %}">3. Перспективы развития методов детектирвоания</a></li>
        </ul>
    </nav>
{% endblock %}

detect/templates/detect/final_test.html
{% extends "detect/base.html" %}
{% load static %}

{% block content %}
    <div class="card-info-bold">{{ len_DB }}{{ zagolovok }}</div>
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ id }}"/>
        <div class="card-interaction">
            <table>
                <div class="text-center"><b>{{ result }}</b></div>
                {{ form }}
            </table>
        </div>
        {% for i in voprosi %}
            {% if i.6 == '0' %}
                <div class="card-content-info size120"><b>{{ i.5 }}. {{ i.0 }}</b><br>
                    <input required type="radio" id="{{ i.5 }}{{ i.1 }}" name="{{ i.5 }}"
                           value="{{ i.1 }}"/>
                    <label for="{{ i.5 }}{{ i.1 }}">{{ i.1 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.2 }}" name="{{ i.5 }}"
                               value="{{ i.2 }}"/>
                    <label for="{{ i.5 }}{{ i.2 }}">{{ i.2 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.3 }}" name="{{ i.5 }}"
                               value="{{ i.3 }}"/>
                    <label for="{{ i.5 }}{{ i.3 }}">{{ i.3 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.4 }}" name="{{ i.5 }}"
                               value="{{ i.4 }}"/>
                    <label for="{{ i.5 }}{{ i.4 }}">{{ i.4 }}</label>
                </div>
            {% else %}
                <div class="card-content-info size120"><b>{{ i.5 }}. {{ i.0 }}</b><br>
                    <img class="bordered-image" style="margin-left: 0;" src={{ i.6 }} alt="{{ i.6 }}"/>
                    <input required type="radio" id="{{ i.5 }}{{ i.1 }}" name="{{ i.5 }}"
                           value="{{ i.1 }}"/>
                    <label for="{{ i.5 }}{{ i.1 }}">{{ i.1 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.2 }}" name="{{ i.5 }}"
                               value="{{ i.2 }}"/>
                    <label for="{{ i.5 }}{{ i.2 }}">{{ i.2 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.3 }}" name="{{ i.5 }}"
                               value="{{ i.3 }}"/>
                    <label for="{{ i.5 }}{{ i.3 }}">{{ i.3 }}</label>

                    <br><input required type="radio" id="{{ i.5 }}{{ i.4 }}" name="{{ i.5 }}"
                               value="{{ i.4 }}"/>
                    <label for="{{ i.5 }}{{ i.4 }}">{{ i.4 }}</label>
                </div>
            {% endif %}
        {% endfor %}
        <div class="text-center" style="margin: 0 1em 1em 1em">
            <button name="submit_button" style="width: 50%; padding: 10px 0;" type="submit" class="orange-button">
                Проверить
            </button>
        </div>
    </form>
{% endblock %}

detect/templates/detect/home.html
{% extends "detect/base.html" %}
{% load text_tags %}
{% block content %}
    <div class="card-content">
        <div class="text-center font-weight-bold h3">{{ header }}</div>
        <div class="card-content-body">{{ text|text_format }}</div>
    </div>
{% endblock %}

detect/templates/detect/laborathory1.html
{% extends "detect/base_laborathory.html" %}
{% load static %}

{% block content %}
    <div class="card">
        <form method="POST">
            {% csrf_token %}
            <p class="card-header">Практическое задание 1</p>
            <p class="card-header">"Изучение влияния SNR на качество детектирования"</p>
            <div class="card-body">
                <input type="hidden" name="Modulation" value="{{ t_modulat }}{{ modulat }}"/>
                <p id="u3870-311">Выбранный тип модуляции: {{ t_modulat }}-{{ modulat }}</p>
                <p>Исходное сообщение, которое будет передаваться по каналу связи: {{ msg }}</p>
                <p>Это сообщение поступает на передающее устройство.</p>
                <p>Внешний вид сообщения после манипуляции {{ t_modulat }}-{{ modulat }} представлен на рисунке 1.</p>
                <img src="/static/detect/lab1/{{ f1 }}.png" alt="{{ f1 }}"/>
                <p id="u3000-40">Рисунок 1 - Внешний вид сообщения после манипуляции {{ t_modulat }}-{{ modulat }}</p>
                <p>Далее этот сигнал передается по каналу связи. В процессе передачи к сигналу добавляются шумы (отношение
                    Сигнал/Шум SNR={{ snr }} дБ). На приёмном устройстве, сигнал, после прохождения через принимающий
                    фильтр, примет вид, изображенный на рисунке 2.</p>
                <img src="/static/detect/lab1/{{ f2 }}.png" alt="{{ f2 }}"/>
                <p id="u3000-40">Рисунок 2 - Внешний вид сообщения после манипуляции {{ t_modulat }}-{{ modulat }} при
                    SNR={{ snr }} дБ</p>
                <p><a id="ssilka" href="##" onclick="collapse('OBL')">Сигнальное созвездие, по которому
                    определяется выходное сообщение, для данного типа манипуляции представлено на рисунке 3: (нажмите, чтобы
                    посмотреть)</a></p>
                <div id="OBL" style="display:none">
                    <img src="/static/detect/graph/{{ t_modulat }}{{ modulat }}.png" alt="{{ t_modulat }}{{ modulat }}"/>
                    <p id="u3000-40">Рисунок 3 - Сигнальное созвездие для {{ t_modulat }}-{{ modulat }} манипуляции</p>
                </div>
                <p>После этапа преобразования сигнала в выборку, происходит процесс детектирования. Сообщение, полученное
                    после детектирования:</p>
                <p>{{ demodulated }}</p>
                <p>Для сравнения - исходное сообщение:</p>
                <p>{{ msg }}</p>
                <center>
                    <div id="u3000-50">
                        <p style="text-indent: 0;">{{ itog }}</p>
                    </div>
                </center>
                {% if c == "0" %}
                    <p>Нажмите на кнопку ниже, чтобы перейти к выполнению следующего задания.</p>
                    <a id="ssilka" class="orange-button" href="{% url 'detect:laboratory2' %}">К заданию 2</a> {# todo не ясно, мб надо к лабе 1 #}
                {% else %}
                    <p>Как видно из рассуждений выше SNR = {{ snr }} дБ не подходит для выполнения условий
                        при {{ t_modulat }}-{{ modulat }} манипуляции. Рассчитайте какое должно быть SNR (формулы для
                        расчёта есть на первой странице задания 1), чтобы получить вероятность ошибки 0.5% и подставьте в
                        окошко ниже.</p>
                    <p><a id="ssilka" href="##" onclick="collapse('formuls')">Формула для расчёта вероятности
                        ошибок (нажмите, чтобы посмотреть)</a></p>
                    <div id="formuls" style="display:none">
                        {% if modulat == "PSK" %}
                            <div id="u3870-90"><img src="{% static "detect/images/formula_MPSK.png" %}" alt="MPSK"/></div>
                        {% else %}
                            <div id="u3870-90"><img src="{% static "detect/images/formula_MQAM.png" %}" alt="MQAM"/></div>
                        {% endif %}
                    </div>
                    <p>Выберите, какое отношение Сигнал/Шум вы хотите сделать:
                        <input placeholder="Пр: 12.5" autocomplete="off" required type="number" name="snr" min="2" max="100"
                               step="0.1"/>
                        дБ
                    </p>
                    <button type="submit" class="orange-button">Проверить</button>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

detect/templates/detect/laboratory1.html
{% extends "detect/base_laborathory.html" %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
    {% if request.user.lab1_is_complete %}
        <div class="card-content-info" style="text-transform: uppercase; text-align: center; font-weight: 600;">
            Вы успешно подобрали SNR для 3 видов сигналов. Зафиксируйте результат и можете перейти к следующей практике!
        </div>
    {% endif %}
    <div class="card-content">
        <p class="text-center font-weight-bold h3">Практическое задание 1</p>
        <p class="text-center font-weight-bold h4">"Изучение влияния SNR на качество детектирования"</p>
        <div class="card-content-body">
            <p id="u3870-311">Выбранный тип модуляции: {{ modulation }}</p>
            <p>Исходное сообщение, которое будет передаваться по каналу связи: {{ original_message }}</p>
            <p>Это сообщение поступает на передающее устройство.</p>
            <p>Внешний вид сообщения после манипуляции {{ modulation }} представлен на рисунке 1.</p>
            <img class="bordered-image" src="{{ path_to_modulated_signal }}" alt="{{ path_to_modulated_signal }}"/>
            <p class="image-caption">Рисунок 1 - Внешний вид сообщения после манипуляции {{ modulation }}</p>
            <p>Далее этот сигнал передается по каналу связи. В процессе передачи к сигналу добавляются шумы (отношение
                Сигнал/Шум SNR={{ snr }} дБ). На приёмном устройстве, сигнал, после прохождения через принимающий
                фильтр, примет вид, изображенный на рисунке 2.</p>
            <img class="bordered-image" src="{{ path_to_signal_with_gauss }}" alt="{{ path_to_signal_with_gauss }}"/>
            <p class="image-caption">Рисунок 2 - Внешний вид сообщения после манипуляции {{ modulation }} при
                SNR={{ snr }} дБ</p>
            <p><a class="link-red" href="##" onclick="collapse('OBL')">Сигнальное созвездие, по которому
                определяется выходное сообщение, для данного типа манипуляции представлено на рисунке 3: (нажмите, чтобы
                посмотреть)</a></p>
            <div id="OBL" style="display:none">
                <img class="bordered-image" src="{{ modulation_image_path }}" alt="{{ modulation_image_path }}"/>
                <p class="image-caption">Рисунок 3 - Сигнальное созвездие для {{ modulation }} манипуляции</p>
            </div>
            <p>После этапа преобразования сигнала в выборку, происходит процесс детектирования. Сообщение, полученное
                после детектирования:</p>
            <p>{{ demodulated_message }}</p>
            <p>Для сравнения - исходное сообщение:</p>
            <p>{{ original_message }}</p>
            {% if is_complete %}
                <div class="card-content-info">
                    <p class="text-indent">
                        Вы справились с заданием, вы подобрали такое SNR, при котором при детектировании 1000 сообщений,
                        с ошибкой было детектировано всего {{ percent_errors }}%, что соответствует условию
                        'около 0.5%'. Зафиксируйте полученный результат.
                    </p>
                </div>
                <p>Нажмите на кнопку ниже, чтобы перейти к выполнению следующего задания.</p>
                <div class="text-center mt-2">
                    <a class="orange-button" href="{% url 'detect:laboratory1' %}">Вернуться к заданию 1</a>
                </div>
            {% else %}
                <p>Как видно из рассуждений выше SNR = {{ snr }} дБ не подходит для выполнения условий
                    при {{ modulation }} манипуляции. Рассчитайте какое должно быть SNR (формулы для
                    расчёта есть на первой странице "Задания 1"), чтобы получить вероятность ошибки 0.5% и подставьте в
                    окно ввода SNR ниже.</p>
                <p><a class="link-red" href="##" onclick="collapse('formula')">Формула для расчёта вероятности
                    ошибок (нажмите, чтобы посмотреть)</a></p>
                <div id="formula" style="display:none">
                    {% if modulat == "PSK" %}
                        <div class="formula-image"><img src="{% static "detect/images/formula_MPSK.png" %}" alt="MPSK"/></div>
                    {% else %}
                        <div class="formula-image"><img src="{% static "detect/images/formula_MQAM.png" %}" alt="MQAM"/></div>
                    {% endif %}
                </div>
                <div class="card-content-info">
                    <p class="text-indent">
                        Продолжайте подбирать SNR. Из 1000 переданных сообщений с ошибкой было детектировано
                        {{ percent_errors }}%, а вам необходимо подобрать такое SNR, при котором вероятность
                        детектирования сообщения с ошибкой будет 'около 0.5%'
                    </p>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    {% bootstrap_field form.modulation show_label=False form_group_class="d-none" %}
                    <div>Выберите, какое отношение Сигнал/Шум (SNR) вы хотите сделать:</div>
                    <div class="d-flex">
                        {% bootstrap_field form.snr show_label=False form_group_class="d-inline-block" %}
                        <div class="d-inline-bock">дБ</div>
                    </div>
                    <div class="text-center mt-2">
                        <button type="submit" class="orange-button">Проверить</button>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

detect/templates/detect/login.html
{% extends "detect/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "detect/css/button.css" %}"/>
{% endblock %}

{% block content %}
    <div class="card-content-info">
        <div class="text-center font-weight-bold h3">Для продолжения работы необходимо ввести данные</div>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="orange-button" type="submit">Перейти к практике</button>
        </form>
    </div>
{% endblock %}

detect/templates/detect/result.html
<!DOCTYPE html>
{% extends "detect/base.html" %}
{% load static %}
{% block content %}
<center><div id="u4000-50">
	<p>{{result}}</p>
</div></center>
{% endblock content %}

detect/templates/detect/result_is_db.html
<!DOCTYPE html>
{% extends "detect/base.html" %}
{% load static %}
{% block content %}
<div id="u5000-50">
	{% for i in spisok %}
		<p>{{i}}</p>
	{% endfor %}
</div>
{% endblock content %}